#!/bin/bash

set -euo pipefail
export IFS=$'\n\t'

name=corydodt/circus-base

ver=$(python -c 'from circusbase import __version__ as v; print v')

docker build -f Dockerfile.ubuntu . -t $name:latest-ubuntu
docker tag $name:latest-ubuntu $name:${ver}-ubuntu
